language: python

python:
  - 2.7

services:
  - mysql

before_install:
  - 'travis_retry sudo apt-get update'
  - 'travis_retry sudo apt-get install libxmlsec1 libxmlsec1-openssl'

install: pip install tox-travis

script: tox
